# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#title"
  weight = 10


[[main]]
  name = "Novedades"
  url = "#posts"
  weight = 20

[[main]]
  name = "Reportes técnicos"
  url = "#publications"
  weight = 40

[[main]]
 name = "Datos abiertos"
  url = "data/"
  weight = 45

#[[main]]
 #name = "Visualizaciones"
 # url = "vis/"
 # weight = 48

[[main]]
  name = "Recursos externos"
  url = "links/"
  weight = 50

[[main]]
  name="¿Quiénes somos?"
  url = "#about"
  weight = 60
  
[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 65

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
